services:
  hackson_support_agent:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/hackson_support_agent:cashed
    command: ["tail", "-f", "/dev/null"]
  
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hack_helper
      POSTGRES_PASSWORD: hackson
      POSTGRES_DB: hackson_support_agent

volumes:
  postgres_data:
